export const countryItems = [
  { label: "Afghanistan 🇦🇫", value: "93", country: "Afghanistan" },
  { label: "Albania 🇦🇱", value: "355", country: "Albania" },
  { label: "Algeria 🇩🇿", value: "213", country: "Algeria" },
  { label: "Andorra 🇦🇩", value: "376", country: "Andorra" },
  { label: "Angola 🇦🇴", value: "244", country: "Angola" },
  { label: "Argentina 🇦🇷", value: "54", country: "Argentina" },
  { label: "Armenia 🇦🇲", value: "374", country: "Armenia" },
  { label: "Australia 🇦🇺", value: "61", country: "Australia" },
  { label: "Austria 🇦🇹", value: "43", country: "Austria" },
  { label: "Azerbaijan 🇦🇿", value: "994", country: "Azerbaijan" },
  { label: "Bahamas 🇧🇸", value: "1-242", country: "Bahamas" },
  { label: "Bahrain 🇧🇭", value: "973", country: "Bahrain" },
  { label: "Bangladesh 🇧🇩", value: "880", country: "Bangladesh" },
  { label: "Barbados 🇧🇧", value: "1-246", country: "Barbados" },
  { label: "Belarus 🇧🇾", value: "375", country: "Belarus" },
  { label: "Belgium 🇧🇪", value: "32", country: "Belgium" },
  { label: "Belize 🇧🇿", value: "501", country: "Belize" },
  { label: "Benin 🇧🇯", value: "229", country: "Benin" },
  { label: "Bhutan 🇧🇹", value: "975", country: "Bhutan" },
  { label: "Bolivia 🇧🇴", value: "591", country: "Bolivia" },
  { label: "Bosnia and Herzegovina 🇧🇦", value: "387", country: "Bosnia and Herzegovina" },
  { label: "Botswana 🇧🇼", value: "267", country: "Botswana" },
  { label: "Brazil 🇧🇷", value: "55", country: "Brazil" },
  { label: "Brunei 🇧🇳", value: "673", country: "Brunei" },
  { label: "Bulgaria 🇧🇬", value: "359", country: "Bulgaria" },
  { label: "Burkina Faso 🇧🇫", value: "226", country: "Burkina Faso" },
  { label: "Burundi 🇧🇮", value: "257", country: "Burundi" },
  { label: "Cape Verde 🇨🇻", value: "238", country: "Cape Verde" },
  { label: "Cambodia 🇰🇭", value: "855", country: "Cambodia" },
  { label: "Cameroon 🇨🇲", value: "237", country: "Cameroon" },
  { label: "Canada 🇨🇦", value: "1", country: "Canada" },
  { label: "Central African Republic 🇨🇫", value: "236", country: "Central African Republic" },
  { label: "Chad 🇹🇩", value: "235", country: "Chad" },
  { label: "Chile 🇨🇱", value: "56", country: "Chile" },
  { label: "China 🇨🇳", value: "86", country: "China" },
  { label: "Colombia 🇨🇴", value: "57", country: "Colombia" },
  { label: "Comoros 🇰🇲", value: "269", country: "Comoros" },
  { label: "Congo 🇨🇬", value: "242", country: "Congo" },
  { label: "Costa Rica 🇨🇷", value: "506", country: "Costa Rica" },
  { label: "Croatia 🇭🇷", value: "385", country: "Croatia" },
  { label: "Cuba 🇨🇺", value: "53", country: "Cuba" },
  { label: "Cyprus 🇨🇾", value: "357", country: "Cyprus" },
  { label: "Czech Republic 🇨🇿", value: "420", country: "Czech Republic" },
  { label: "Denmark 🇩🇰", value: "45", country: "Denmark" },
  { label: "Djibouti 🇩🇯", value: "253", country: "Djibouti" },
  { label: "Dominica 🇩🇲", value: "1-767", country: "Dominica" },
  { label: "Dominican Republic 🇩🇴", value: "1-809", country: "Dominican Republic" },
  { label: "Ecuador 🇪🇨", value: "593", country: "Ecuador" },
  { label: "Egypt 🇪🇬", value: "20", country: "Egypt" },
  { label: "El Salvador 🇸🇻", value: "503", country: "El Salvador" },
  { label: "Equatorial Guinea 🇬🇶", value: "240", country: "Equatorial Guinea" },
  { label: "Eritrea 🇪🇷", value: "291", country: "Eritrea" },
  { label: "Estonia 🇪🇪", value: "372", country: "Estonia" },
  { label: "Eswatini 🇸🇿", value: "268", country: "Eswatini" },
  { label: "Ethiopia 🇪🇹", value: "251", country: "Ethiopia" },
  { label: "Fiji 🇫🇯", value: "679", country: "Fiji" },
  { label: "Finland 🇫🇮", value: "358", country: "Finland" },
  { label: "France 🇫🇷", value: "33", country: "France" },
  { label: "Gabon 🇬🇦", value: "241", country: "Gabon" },
  { label: "Gambia 🇬🇲", value: "220", country: "Gambia" },
  { label: "Georgia 🇬🇪", value: "995", country: "Georgia" },
  { label: "Germany 🇩🇪", value: "49", country: "Germany" },
  { label: "Ghana 🇬🇭", value: "233", country: "Ghana" },
  { label: "Greece 🇬🇷", value: "30", country: "Greece" },
  { label: "Grenada 🇬🇩", value: "1-473", country: "Grenada" },
  { label: "Guatemala 🇬🇹", value: "502", country: "Guatemala" },
  { label: "Guinea 🇬🇳", value: "224", country: "Guinea" },
  { label: "Guinea-Bissau 🇬🇼", value: "245", country: "Guinea-Bissau" },
  { label: "Guyana 🇬🇾", value: "592", country: "Guyana" },
  { label: "Haiti 🇭🇹", value: "509", country: "Haiti" },
  { label: "Honduras 🇭🇳", value: "504", country: "Honduras" },
  { label: "Hungary 🇭🇺", value: "36", country: "Hungary" },
  { label: "Iceland 🇮🇸", value: "354", country: "Iceland" },
  { label: "India 🇮🇳", value: "91", country: "India" },
  { label: "Indonesia 🇮🇩", value: "62", country: "Indonesia" },
  { label: "Iran 🇮🇷", value: "98", country: "Iran" },
  { label: "Iraq 🇮🇶", value: "964", country: "Iraq" },
  { label: "Ireland 🇮🇪", value: "353", country: "Ireland" },
  { label: "Israel 🇮🇱", value: "972", country: "Israel" },
  { label: "Italy 🇮🇹", value: "39", country: "Italy" },
  { label: "Jamaica 🇯🇲", value: "1-876", country: "Jamaica" },
  { label: "Japan 🇯🇵", value: "81", country: "Japan" },
  { label: "Jordan 🇯🇴", value: "962", country: "Jordan" },
  { label: "Kazakhstan 🇰🇿", value: "7", country: "Kazakhstan" },
  { label: "Kenya 🇰🇪", value: "254", country: "Kenya" },
  { label: "Kiribati 🇰🇮", value: "686", country: "Kiribati" },
  { label: "Kuwait 🇰🇼", value: "965", country: "Kuwait" },
  { label: "Kyrgyzstan 🇰🇬", value: "996", country: "Kyrgyzstan" },
  { label: "Laos 🇱🇦", value: "856", country: "Laos" },
  { label: "Latvia 🇱🇻", value: "371", country: "Latvia" },
  { label: "Lebanon 🇱🇧", value: "961", country: "Lebanon" },
  { label: "Lesotho 🇱🇸", value: "266", country: "Lesotho" },
  { label: "Liberia 🇱🇷", value: "231", country: "Liberia" },
  { label: "Libya 🇱🇾", value: "218", country: "Libya" },
  { label: "Liechtenstein 🇱🇮", value: "423", country: "Liechtenstein" },
  { label: "Lithuania 🇱🇹", value: "370", country: "Lithuania" },
  { label: "Luxembourg 🇱🇺", value: "352", country: "Luxembourg" },
  { label: "Madagascar 🇲🇬", value:  "261", country: "Madagascar" },
  { label: "Malawi 🇲🇼", value: "265", country: "Malawi" },
  { label: "Malaysia 🇲🇾", value: "60", country: "Malaysia" },
  { label: "Maldives 🇲🇻", value: "960", country: "Maldives" },
  { label: "Mali 🇲🇱", value: "223", country: "Mali" },
  { label: "Malta 🇲🇹", value: "356", country: "Malta" },
  { label: "Marshall Islands 🇲🇭", value: "692", country: "Marshall Islands" },
  { label: "Mauritania 🇲🇷", value: "222", country: "Mauritania" },
  { label: "Mauritius 🇲🇺", value: "230", country: "Mauritius" },
  { label: "Mexico 🇲🇽", value: "52", country: "Mexico" },
  { label: "Micronesia 🇫🇲", value: "691", country: "Micronesia" },
  { label: "Moldova 🇲🇩", value: "373", country: "Moldova" },
  { label: "Monaco 🇲🇨", value: "377", country: "Monaco" },
  { label: "Mongolia 🇲🇳", value: "976", country: "Mongolia" },
  { label: "Montenegro 🇲🇪", value: "382", country: "Montenegro" },
  { label: "Morocco 🇲🇦", value: "212", country: "Morocco" },
  { label: "Mozambique 🇲🇿", value: "258", country: "Mozambique" },
  { label: "Myanmar 🇲🇲", value: "95", country: "Myanmar" },
  { label: "Namibia 🇳🇦", value: "264", country: "Namibia" },
  { label: "Nauru 🇳🇷", value: "674", country: "Nauru" },
  { label: "Nepal 🇳🇵", value: "977", country: "Nepal" },
  { label: "Netherlands 🇳🇱", value: "31", country: "Netherlands" },
  { label: "New Zealand 🇳🇿", value: "64", country: "New Zealand" },
  { label: "Nicaragua 🇳🇮", value: "505", country: "Nicaragua" },
  { label: "Niger 🇳🇪", value: "227", country: "Niger" },
  { label: "Nigeria 🇳🇬", value: "234", country: "Nigeria" },
  { label: "North Korea 🇰🇵", value: "850", country: "North Korea" },
  { label: "North Macedonia 🇲🇰", value: "389", country: "North Macedonia" },
  { label: "Norway 🇳🇴", value: "47", country: "Norway" },
  { label: "Oman 🇴🇲", value: "968", country: "Oman" },
  { label: "Pakistan 🇵🇰", value: "92", country: "Pakistan" },
  { label: "Palau 🇵🇼", value: "680", country: "Palau" },
  { label: "Palestine 🇵🇸", value: "970", country: "Palestine" },
  { label: "Panama 🇵🇦", value: "507", country: "Panama" },
  { label: "Papua New Guinea 🇵🇬", value: "675", country: "Papua New Guinea" },
  { label: "Paraguay 🇵🇾", value: "595", country: "Paraguay" },
  { label: "Peru 🇵🇪", value: "51", country: "Peru" },
  { label: "Philippines 🇵🇭", value: "63", country: "Philippines" },
  { label: "Poland 🇵🇱", value: "48", country: "Poland" },
  { label: "Portugal 🇵🇹", value: "351", country: "Portugal" },
  { label: "Qatar 🇶🇦", value: "974", country: "Qatar" },
  { label: "Romania 🇷🇴", value: "40", country: "Romania" },
  { label: "Russia 🇷🇺", value: "7", country: "Russia" },
  { label: "Rwanda 🇷🇼", value: "250", country: "Rwanda" },
  { label: "Saint Kitts and Nevis 🇰🇳", value: "1-869", country: "Saint Kitts and Nevis" },
  { label: "Saint Lucia 🇱🇨", value: "1-758", country: "Saint Lucia" },
  { label: "Saint Vincent and the Grenadines 🇻🇨", value: "1-784", country: "Saint Vincent and the Grenadines" },
  { label: "Samoa 🇼🇸", value: "685", country: "Samoa" },
  { label: "San Marino 🇸🇲", value: "378", country: "San Marino" },
  { label: "Sao Tome and Principe 🇸🇹", value: "239", country: "Sao Tome and Principe" },
  { label: "Saudi Arabia 🇸🇦", value: "966", country: "Saudi Arabia" },
  { label: "Senegal 🇸🇳", value: "221", country: "Senegal" },
  { label: "Serbia 🇷🇸", value: "381", country: "Serbia" },
  { label: "Seychelles 🇸🇨", value: "248", country: "Seychelles" },
  { label: "Sierra Leone 🇸🇱", value: "232", country: "Sierra Leone" },
  { label: "Singapore 🇸🇬", value: "65", country: "Singapore" },
  { label: "Slovakia 🇸🇰", value: "421", country: "Slovakia" },
  { label: "Slovenia 🇸🇮", value: "386", country: "Slovenia" },
  { label: "Solomon Islands 🇸🇧", value: "677", country: "Solomon Islands" },
  { label: "Somalia 🇸🇴", value: "252", country: "Somalia" },
  { label: "South Africa 🇿🇦", value: "27", country: "South Africa" },
  { label: "South Korea 🇰🇷", value: "82", country: "South Korea" },
  { label: "South Sudan 🇸🇸", value: "211", country: "South Sudan" },
  { label: "Spain 🇪🇸", value: "34", country: "Spain" },
  { label: "Sri Lanka 🇱🇰", value: "94", country: "Sri Lanka" },
  { label: "Sudan 🇸🇩", value: "249", country: "Sudan" },
  { label: "Suriname 🇸🇷", value: "597", country: "Suriname" },
  { label: "Sweden 🇸🇪", value: "46", country: "Sweden" },
  { label: "Switzerland 🇨🇭", value: "41", country: "Switzerland" },
  { label: "Syria 🇸🇾", value: "963", country: "Syria" },
  { label: "Taiwan 🇹🇼", value: "886", country: "Taiwan" },
  { label: "Tajikistan 🇹🇯", value: "992", country: "Tajikistan" },
  { label: "Tanzania 🇹🇿", value: "255", country: "Tanzania" },
  { label: "Thailand 🇹🇭", value: "66", country: "Thailand" },
  { label: "Timor-Leste 🇹🇱", value: "670", country: "Timor-Leste" },
  { label: "Togo 🇹🇬", value: "228", country: "Togo" },
  { label: "Tokelau 🇹🇰", value: "690", country: "Tokelau" },
  { label: "Tonga 🇹🇴", value: "676", country: "Tonga" },
  { label: "Trinidad and Tobago 🇹🇹", value: "1-868", country: "Trinidad and Tobago" },
  { label: "Tunisia 🇹🇳", value: "216", country: "Tunisia" },
  { label: "Turkey 🇹🇷", value: "90", country: "Turkey" },
  { label: "Turkmenistan 🇹🇲", value: "993", country: "Turkmenistan" },
  { label: "Tuvalu 🇹🇻", value: "688", country: "Tuvalu" },
  { label: "Uganda 🇺🇬", value: "256", country: "Uganda" },
  { label: "Ukraine 🇺🇦", value: "380", country: "Ukraine" },
  { label: "United Arab Emirates 🇦🇪", value: "971", country: "United Arab Emirates" },
  { label: "United Kingdom 🇬🇧", value: "44", country: "United Kingdom" },
  { label: "Uruguay 🇺🇾", value: "598", country: "Uruguay" },
  { label: "Uzbekistan 🇺🇿", value: "998", country: "Uzbekistan" },
  { label: "Vanuatu 🇻🇺", value: "678", country: "Vanuatu" },
  { label: "Venezuela 🇻🇪", value: "58", country: "Venezuela" },
  { label: "Vietnam 🇻🇳", value: "84", country: "Vietnam" },
  { label: "Yemen 🇾🇪", value: "967", country: "Yemen" },
  { label: "Zambia 🇿🇲", value: "260", country: "Zambia" },
  { label: "Zimbabwe 🇿🇼", value: "263", country: "Zimbabwe" },
];