export const countryItems = [
  { label: "+93 🇦🇫", value: "93", country: "Afghanistan" },
  { label: "+355 🇦🇱", value: "355", country: "Albania" },
  { label: "+213 🇩🇿", value: "213", country: "Algeria" },
  { label: "+376 🇦🇩", value: "376", country: "Andorra" },
  { label: "+244 🇦🇴", value: "244", country: "Angola" },
  { label: "+54 🇦🇷", value: "54", country: "Argentina" },
  { label: "+374 🇦🇲", value: "374", country: "Armenia" },
  { label: "+61 🇦🇺", value: "61", country: "Australia" },
  { label: "+43 🇦🇹", value: "43", country: "Austria" },
  { label: "+994 🇦🇿", value: "994", country: "Azerbaijan" },
  { label: "+1-242 🇧🇸", value: "1-242", country: "Bahamas" },
  { label: "+973 🇧🇭", value: "973", country: "Bahrain" },
  { label: "+880 🇧🇩", value: "880", country: "Bangladesh" },
  { label: "+1-246 🇧🇧", value: "1-246", country: "Barbados" },
  { label: "+375 🇧🇾", value: "375", country: "Belarus" },
  { label: "+32 🇧🇪", value: "32", country: "Belgium" },
  { label: "+501 🇧🇿", value: "501", country: "Belize" },
  { label: "+229 🇧🇯", value: "229", country: "Benin"},
  { label: "+975 🇧🇹", value: "975", country: "Bhutan" },
  { label: "+591 🇧🇴", value: "591", country: "Bolivia" },
  { label: "+387 🇧🇦", value: "387", country: "Bosnia and Herzegovina" },
  { label: "+267 🇧🇼", value: "267", country: "Botswana" },
  { label: "+55 🇧🇷", value: "55", country: "Brazil" },
  { label: "+673 🇧🇳", value: "673", country: "Brunei" },
  { label: "+359 🇧🇬", value: "359", country: "Bulgaria" },
  { label: "+226 🇧🇫", value: "226", country: "Burkina Faso" },
  { label: "+257 🇧🇮", value: "257", country: "Burundi" },
  { label: "+238 🇨🇻", value: "238", country: "Cape Verde" },
  { label: "+855 🇰🇭", value: "855", country: "Cambodia" },
  { label: "+237 🇨🇲", value: "237", country: "Cameroon" },
  { label: "+1 🇨🇦", value: "1", country: "Canada" },
  { label: "+236 🇨🇫", value: "236", country: "Central African Republic" },
  { label: "+235 🇹🇩", value: "235", country: "Chad" },
  { label: "+56 🇨🇱", value: "56", country: "Chile" },
  { label: "+86 🇨🇳", value: "86", country: "China" },
  { label: "+57 🇨🇴", value: "57", country: "Colombia" },
  { label: "+269 🇰🇲", value: "269", country: "Comoros" },
  { label: "+242 🇨🇬", value: "242", country: "Congo" },
  { label: "+506 🇨🇷", value: "506", country: "Costa Rica" },
  { label: "+385 🇭🇷", value: "385", country: "Croatia" },
  { label: "+53 🇨🇺", value: "53", country: "Cuba" },
  { label: "+357 🇨🇾", value: "357", country: "Cyprus" },
  { label: "+420 🇨🇿", value: "420", country: "Czech Republic" },
  { label: "+45 🇩🇰", value: "45", country: "Denmark" },
  { label: "+253 🇩🇯", value: "253", country: "Djibouti" },
  { label: "+1-767 🇩🇲", value: "1-767", country: "Dominica" },
  { label: "+1-809 🇩🇴", value: "1-809", country: "Dominican Republic" },
  { label: "+593 🇪🇨", value: "593", country: "Ecuador" },
  { label: "+20 🇪🇬", value: "20", country: "Egypt" },
  { label: "+503 🇸🇻", value: "503", country: "El Salvador" },
  { label: "+240 🇬🇶", value: "240", country: "Equatorial Guinea" },
  { label: "+291 🇪🇷", value: "291", country: "Eritrea" },
  { label: "+372 🇪🇪", value: "372", country: "Estonia" },
  { label: "+268 🇸🇿", value: "268", country: "Eswatini" },
  { label: "+251 🇪🇹", value: "251", country: "Ethiopia" },
  { label: "+679 🇫🇯", value: "679", country: "Fiji" },
  { label: "+358 🇫🇮", value: "358", country: "Finland" },
  { label: "+33 🇫🇷", value: "33", country: "France" },
  { label: "+241 🇬🇦", value: "241", country: "Gabon" },
  { label: "+220 🇬🇲", value: "220", country: "Gambia" },
  { label: "+995 🇬🇪", value: "995", country: "Georgia" },
  { label: "+49 🇩🇪", value: "49", country: "Germany" },
  { label: "+233 🇬🇭", value: "233", country: "Ghana" },
  { label: "+30 🇬🇷", value: "30", country: "Greece" },
  { label: "+1-473 🇬🇩", value: "1-473", country: "Grenada" },
  { label: "+502 🇬🇹", value: "502", country: "Guatemala" },
  { label: "+224 🇬🇳", value: "224", country: "Guinea" },
  { label: "+245 🇬🇼", value: "245", country: "Guinea-Bissau" },
  { label: "+592 🇬🇾", value: "592", country: "Guyana" },
  { label: "+509 🇭🇹", value: "509", country: "Haiti" },
  { label: "+504 �HN", value: "504", country: "Honduras" },
  { label: "+36 🇭🇺", value: "36", country: "Hungary" },
  { label: "+354 🇮🇸", value: "354", country: "Iceland" },
  { label: "+91 🇮🇳", value: "91", country: "India" },
  { label: "+62 🇮🇩", value: "62", country: "Indonesia" },
  { label: "+98 🇮🇷", value: "98", country: "Iran" },
  { label: "+964 🇮🇶", value: "964", country: "Iraq" },
  { label: "+353 🇮🇪", value: "353", country: "Ireland" },
  { label: "+972 🇮🇱", value: "972", country: "Israel" },
  { label: "+39 🇮🇹", value: "39", country: "Italy" },
  { label: "+1-876 🇯🇲", value: "1-876", country: "Jamaica" },
  { label: "+81 🇯🇵", value: "81", country: "Japan" },
  { label: "+962 🇯🇴", value: "962", country: "Jordan" },
  { label: "+7 🇰🇿", value: "7", country: "Kazakhstan" },
  { label: "+254 🇰🇪", value: "254", country: "Kenya" },
  { label: "+686 🇰🇮", value: "686", country: "Kiribati" },
  { label: "+965 🇰🇼", value: "965", country: "Kuwait" },
  { label: "+996 🇰🇬", value: "996", country: "Kyrgyzstan" },
  { label: "+856 🇱🇦", value: "856", country: "Laos" },
  { label: "+371 🇱🇻", value: "371", country: "Latvia" },
  { label: "+961 🇱🇧", value: "961", country: "Lebanon" },
  { label: "+266 🇱🇸", value: "266", country: "Lesotho" },
  { label: "+231 🇱🇷", value: "231", country: "Liberia" },
  { label: "+218 🇱🇾", value: "218", country: "Libya" },
  { label: "+423 🇱🇮", value: "423", country: "Liechtenstein" },
  { label: "+370 🇱🇹", value: "370", country: "Lithuania" },
  { label: "+352 🇱🇺", value: "352", country: "Luxembourg" },
  { label: "+261 🇲🇬", value: "261", country: "Madagascar" },
  { label: "+265 🇲🇼", value: "265", country: "Malawi" },
  { label: "+60 🇲🇾", value: "60", country: "Malaysia" },
  { label: "+960 🇲🇻", value: "960", country: "Maldives" },
  { label: "+223 🇲🇱", value: "223", country: "Mali" },
  { label: "+356 🇲🇹", value: "356", country: "Malta" },
  { label: "+692 🇲🇭", value: "692", country: "Marshall Islands" },
  { label: "+222 🇲🇷", value: "222", country: "Mauritania" },
  { label: "+230 🇲🇺", value: "230", country: "Mauritius" },
  { label: "+52 🇲🇽", value: "52", country: "Mexico" },
  { label: "+691 🇫🇲", value: "691", country: "Micronesia" },
  { label: "+373 🇲🇩", value: "373", country: "Moldova" },
  { label: "+377 🇲🇨", value: "377", country: "Monaco" },
  { label: "+976 🇲🇳", value: "976", country: "Mongolia" },
  { label: "+382 🇲🇪", value: "382", country: "Montenegro" },
  { label: "+212 🇲🇦", value: "212", country: "Morocco" },
  { label: "+258 🇲🇿", value: "258", country: "Mozambique" },
  { label: "+95 🇲🇲", value: "95", country: "Myanmar" },
  { label: "+264 🇳🇦", value: "264", country: "Namibia" },
  { label: "+674 🇳🇷", value: "674", country: "Nauru" },
  { label: "+977 🇳🇵", value: "977", country: "Nepal" },
  { label: "+31 🇳🇱", value: "31", country: "Netherlands" },
  { label: "+64 🇳🇿", value: "64", country: "New Zealand" },
  { label: "+505 🇳🇮", value: "505", country: "Nicaragua" },
  { label: "+227 🇳🇪", value: "227", country: "Niger" },
  { label: "+234 🇳🇬", value: "234", country: "Nigeria" },
  { label: "+850 🇰🇵", value: "850", country: "North Korea" },
  { label: "+389 🇲🇰", value: "389", country: "North Macedonia" },
  { label: "+47 🇳🇴", value: "47", country: "Norway" },
  { label: "+968 🇴🇲", value: "968", country: "Oman" },
  { label: "+92 🇵🇰", value: "92", country: "Pakistan" },
  { label: "+680 🇵🇼", value: "680", country: "Palau" },
  { label: "+970 🇵🇸", value: "970", country: "Palestine" },
  { label: "+507 🇵🇦", value: "507", country: "Panama" },
  { label: "+675 🇵🇬", value: "675", country: "Papua New Guinea" },
  { label: "+595 🇵🇾", value: "595", country: "Paraguay" },
  { label: "+51 🇵🇪", value: "51", country: "Peru" },
  { label: "+63 🇵🇭", value: "63", country: "Philippines" },
  { label: "+48 🇵🇱", value: "48", country: "Poland" },
  { label: "+351 🇵🇹", value: "351", country: "Portugal" },
  { label: "+974 🇶🇦", value: "974", country: "Qatar" },
  { label: "+40 🇷🇴", value: "40", country: "Romania" },
  { label: "+7 🇷🇺", value: "7", country: "Russia" },
  { label: "+250 🇷🇼", value: "250", country: "Rwanda" },
  { label: "+1-869 🇰🇳", value: "1-869", country: "Saint Kitts and Nevis" },
  { label: "+1-758 🇱🇨", value: "1-758", country: "Saint Lucia" },
  { label: "+1-784 🇻🇨", value: "1-784", country: "Saint Vincent and the Grenadines" },
  { label: "+685 🇼🇸", value: "685", country: "Samoa" },
  { label: "+378 🇸🇲", value: "378", country: "San Marino" },
  { label: "+239 🇸🇹", value: "239", country: "Sao Tome and Principe" },
  { label: "+966 🇸🇦", value: "966", country: "Saudi Arabia" },
  { label: "+221 🇸🇳", value: "221", country: "Senegal" },
  { label: "+381 🇷🇸", value: "381", country: "Serbia" },
  { label: "+248 🇸🇨", value: "248", country: "Seychelles" },
  { label: "+232 🇸🇱", value: "232", country: "Sierra Leone" },
  { label: "+65 🇸🇬", value: "65", country: "Singapore" },
  { label: "+421 🇸🇰", value: "421", country: "Slovakia" },
  { label: "+386 🇸🇮", value: "386", country: "Slovenia" },
  { label: "+677 🇸🇧", value: "677", country: "Solomon Islands" },
  { label: "+252 🇸🇴", value: "252", country: "Somalia" },
  { label: "+27 🇿🇦", value: "27", country: "South Africa" },
  { label: "+82 🇰🇷", value: "82", country: "South Korea" },
  { label: "+211 🇸🇸", value: "211", country: "South Sudan" },
  { label: "+34 🇪🇸", value: "34", country: "Spain" },
  { label: "+94 🇱🇰", value: "94", country: "Sri Lanka" },
  { label: "+249 🇸🇩", value: "249", country: "Sudan" },
  { label: "+597 🇸🇷", value: "597", country: "Suriname" },
  { label: "+46 🇸🇪", value: "46", country: "Sweden" },
  { label: "+41 🇨🇭", value: "41", country: "Switzerland" },
  { label: "+963 🇸🇾", value: "963", country: "Syria" },
  { label: "+886 🇹🇼", value: "886", country: "Taiwan" },
  { label: "+992 🇹🇯", value: "992", country: "Tajikistan" },
  { label: "+255 🇹🇿", value: "255", country: "Tanzania" },
  { label: "+66 🇹🇭", value: "66", country: "Thailand" },
  { label: "+670 🇹🇱", value: "670", country: "Timor-Leste" },
  { label: "+228 🇹🇬", value: "228", country: "Togo" },
  { label: "+690 🇹🇰", value: "690", country: "Tokelau" },
  { label: "+676 🇹🇴", value: "676", country: "Tonga" },
  { label: "+1-868 🇹🇹", value: "1-868", country: "Trinidad and Tobago" },
  { label: "+216 🇹🇳", value: "216", country: "Tunisia" },
  { label: "+90 🇹🇷", value: "90", country: "Turkey" },
  { label: "+993 🇹🇲", value: "993", country: "Turkmenistan" },
  { label: "+688 🇹🇻", value: "688", country: "Tuvalu" },
  { label: "+256 🇺🇬", value: "256", country: "Uganda" },
  { label: "+380 🇺🇦", value: "380", country: "Ukraine" },
  { label: "+971 🇦🇪", value: "971", country: "United Arab Emirates" },
  { label: "+44 🇬🇧", value: "44", country: "United Kingdom" },
  { label: "+598 🇺🇾", value: "598", country: "Uruguay" },
  { label: "+998 🇺🇿", value: "998", country: "Uzbekistan" },
  { label: "+678 🇻🇺", value: "678", country: "Vanuatu" },
  { label: "+58 🇻🇪", value: "58", country: "Venezuela" },
  { label: "+84 🇻🇳", value: "84", country: "Vietnam" },
  { label: "+967 🇾🇪", value: "967", country: "Yemen" },
  { label: "+260 🇿🇲", value: "260", country: "Zambia" },
  { label: "+263 🇿🇼", value: "263", country: "Zimbabwe" },
];